spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: customer


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    register-with-eureka: true
    fetch-registry: true